const{chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/kgood/.codex/skills/develop-web-game/node_modules/playwright'),{books,text,route}=require('./frontend-fixture.cjs'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const OUT=process.env.BOOK_EVIDENCE||path.resolve(__dirname,'../../.visual-review/next-trio/books/tests');fs.mkdirSync(OUT,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});const checks=[],errors=[],writes=[];const check=(name,ok)=>{assert(ok,name);checks.push({name,pass:true});};let mode='',activeWrites=0,maxWrites=0;const sleep=ms=>new Promise(r=>setTimeout(r,ms));
try{const c=await browser.newContext({viewport:{width:600,height:600}});await route(c,{handle:async(r,u)=>{
 const method=r.request().method();
 if(u.pathname.startsWith('/api/me')){if(method!=='GET'){const started=Date.now(),payload=r.request().postDataJSON();if(u.pathname.includes('/progress/')){activeWrites++;maxWrites=Math.max(maxWrites,activeWrites);if(mode==='slow-write')await sleep(1400);activeWrites--;}writes.push({url:u.pathname,method,payload,started,ended:Date.now(),identity:r.request().headers()['x-device-id']});await r.fulfill({status:mode==='sync-fail'?503:200,json:{ok:true}});return true;}await r.fulfill({json:u.pathname.endsWith('/favorites')?{favorites:[]} :u.pathname.endsWith('/recents')?{recents:[]}:{fraction:0,updatedAt:0}});return true;}
 if(mode==='popular-race'&&u.pathname==='/api/books'&&!u.searchParams.has('search')){await sleep(650);await r.fulfill({json:{results:books,next:null}});return true;}
 if(u.pathname==='/api/books'&&u.searchParams.has('search')){const q=u.searchParams.get('search');if(q==='slow')await sleep(550);await r.fulfill({json:{results:[q==='fast'?books[1]:books[0]],next:null}});return true;}
 if((mode==='book-race'||mode==='loading-exit')&&(u.pathname.includes('/1342/content')||u.pathname==='/api/proxy')){await sleep(850);try{await r.fulfill({contentType:'text/plain',body:text});}catch{}return true;}
 if(mode==='book-race'&&u.pathname.includes('/11/content')){await r.fulfill({contentType:'text/plain',body:'ALICE ONLY.\n\n'+text});return true;}
 if(mode==='text-error'&&(u.pathname.endsWith('/content')||u.pathname==='/api/proxy')){await r.fulfill({status:503,body:'Unavailable'});return true;}
 return false;
 }});const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:5213/?test=1');await p.waitForTimeout(150);const identity=await p.evaluate(()=>localStorage.getItem('mdg_book_reader_v1:device'));check('Meta display capability and three original cover previews',await p.locator('meta[name=mrbd-web-app-capable]').getAttribute('content')==='yes'&&await p.locator('.featured-book').count()===3);
await p.locator('[data-action=go-browse]').focus();await p.evaluate(()=>document.activeElement.click());await p.waitForTimeout(100);check('focused-element pinch opens catalog and focuses first book',await p.locator('#browse').isVisible()&&await p.evaluate(()=>document.activeElement.classList.contains('book-item')));
await p.keyboard.press('ArrowRight');check('spatial Right moves to second book',await p.evaluate(()=>document.activeElement.dataset.bookId==='11'));await p.keyboard.press('ArrowUp');check('Up reaches tabs from books',await p.evaluate(()=>document.activeElement.classList.contains('tab-item')));
mode='popular-race';await p.evaluate(()=>{__readerTest.state.cache={};__readerTest.action('browse-tab',{dataset:{tab:'popular'}});});await p.locator('[data-tab=adventure]').click();const adventure=await p.locator('#browse-list').innerText();await p.waitForTimeout(800);check('late Popular cannot replace newer Adventure tab',await p.locator('#browse-list').innerText()===adventure);mode='';
await p.keyboard.press('Escape');await p.locator('[data-action=go-search]').click();await p.locator('#search-input').fill('slow');await p.locator('[data-action=run-search]').click();await p.locator('#search-input').fill('fast');await p.locator('[data-action=run-search]').click();await p.waitForTimeout(700);check('latest search wins over late earlier query',await p.locator('#search-results .book-item').first().getAttribute('data-book-id')==='11');
await p.locator('#search-input').fill('');await p.locator('#keyboard-toggle').click();let seen=new Set();for(const key of ['A','B','C','D','E','F','G']){seen.add(await p.evaluate(()=>document.activeElement.dataset.letter));await p.keyboard.press('ArrowRight');}check('D-pad keyboard traverses first seven letters',seen.size===7);await p.locator('[data-letter=A]').focus();await p.evaluate(()=>document.activeElement.click());await p.locator('[data-letter=space]').click();await p.locator('[data-letter=B]').click();await p.locator('[data-letter=delete]').click();check('letter keyboard types and deletes without native keyboard',await p.locator('#search-input').inputValue()==='a ');await p.locator('[data-action=run-search]').click();await p.waitForTimeout(80);check('search hides spelling grid and returns results',await p.locator('#search-keyboard').isHidden()&&await p.locator('#search-results .book-item').count()===1);
await p.locator('#search-results .book-item').click();await p.waitForTimeout(80);check('detail starts on Read, not Back',await p.evaluate(()=>document.activeElement.dataset.action==='open-book'));await p.locator('#detail-favorite-btn').click();check('favorite persists locally immediately',await p.evaluate(()=>!!JSON.parse(localStorage.getItem('mdg_book_reader_v1')).favorites[1342]));await p.locator('[data-action=open-book]').click();await p.waitForFunction(()=>__readerTest.state.reader.ready);check('reader is ready with page controls',await p.locator('#page-forward').isEnabled()&&await p.locator('#page-back').isDisabled());await p.screenshot({path:path.join(OUT,'reader-600.png')});
await p.keyboard.press('ArrowRight');await p.keyboard.press('ArrowRight');await p.waitForTimeout(30);check('Right turns pages in reading mode',await p.evaluate(()=>__readerTest.state.reader.currentPage===2));await p.evaluate(()=>document.activeElement.click());check('coordinate-free pinch on reading area opens menu',await p.locator('#reader-menu').isVisible());
let menuActions=new Set();for(let i=0;i<8;i++){menuActions.add(await p.evaluate(()=>document.activeElement.dataset.action));await p.keyboard.press('Tab');}check('modal Tab remains inside reading menu',await p.evaluate(()=>!!document.activeElement.closest('#reader-menu')));const anchor=await p.evaluate(()=>__readerTest.state.reader.anchorOffset);await p.locator('#reader-menu [data-action=text-size-up]').click();await p.locator('#reader-menu [data-action=text-size-down]').click();await p.locator('#reader-menu [data-action=line-spacing-up]').click();await p.locator('#reader-menu [data-action=line-spacing-down]').click();check('text and spacing reflow preserve exact source anchor',await p.evaluate(a=>__readerTest.state.reader.anchorOffset===a,anchor));await p.locator('[data-action=close-reader-menu]').click();check('closing menu returns focus to reading surface',await p.evaluate(()=>document.activeElement.id==='reader-page'));await p.setViewportSize({width:390,height:844});check('resize preserves exact source anchor',await p.evaluate(a=>__readerTest.state.reader.anchorOffset===a,anchor));await p.setViewportSize({width:600,height:600});
const pagination=await p.evaluate(()=>{const r=__readerTest.state.reader,inner=document.querySelector('#reader-page-inner'),box=document.querySelector('#reader-page');let over=[],combined='';r.pages.forEach((html,i)=>{inner.innerHTML=html;combined+=inner.textContent.replace(/\s/g,'');if(inner.scrollHeight>box.clientHeight+1)over.push(i);});__readerTest.seek(r.anchorOffset);return{overflow:over,complete:combined===r.text.replace(/\s/g,''),pages:r.pages.length};});check('every generated page fits its viewport',pagination.overflow.length===0);check('pagination loses or duplicates no content',pagination.complete);
mode='slow-write';await p.locator('#page-forward').click();await p.waitForTimeout(700);await p.locator('#page-forward').click();await p.waitForTimeout(700);await p.locator('#page-forward').click();await p.waitForTimeout(700);await p.waitForFunction(()=>!__readerTest.state.data.syncQueue['progress:1342'],{},{timeout:8000});check('progress requests are serialized per book',maxWrites===1);const progressWrites=writes.filter(w=>w.url.includes('/progress/'));check('last completed progress matches latest page',Math.abs(progressWrites.at(-1).payload.fraction-await p.evaluate(()=>__readerTest.state.data.progress[1342].fraction))<.000001);mode='';
await p.evaluate(()=>window.dispatchEvent(new Event('pagehide')));const saved=await p.evaluate(()=>JSON.parse(localStorage.getItem('mdg_book_reader_v1')).progress[1342]);await p.reload();await p.waitForTimeout(150);await p.locator('[data-action=resume-reading]').click();await p.waitForFunction(()=>__readerTest.state.reader.ready);check('reload resumes exact saved offset and identity',await p.evaluate(s=>__readerTest.state.reader.anchorOffset===s.offset,saved)&&await p.evaluate(()=>localStorage.getItem('mdg_book_reader_v1:device'))===identity);
await p.keyboard.press('Escape');await p.locator('#home-featured [data-book-id="1342"]').click();mode='loading-exit';const beforeLoading=await p.evaluate(()=>JSON.stringify(__readerTest.state.data.progress[1342]));await p.locator('[data-action=open-book]').click();await p.locator('#reader-toolbar [data-action=back]').click();await p.waitForTimeout(1000);check('leaving pending load preserves progress and does not reopen reader',await p.evaluate(s=>JSON.stringify(__readerTest.state.data.progress[1342])===s&&__readerTest.state.currentScreen==='book-detail',beforeLoading));
mode='book-race';await p.locator('[data-action=open-book]').click();await p.locator('#reader-toolbar [data-action=back]').click();await p.keyboard.press('Escape');await p.keyboard.press('Escape');await p.locator('#home-featured [data-book-id="11"]').click();await p.locator('[data-action=open-book]').click();await p.waitForFunction(()=>__readerTest.state.reader.ready);await p.waitForTimeout(1100);check('late book A cannot corrupt book B text, identity, or recents',await p.evaluate(()=>__readerTest.state.reader.bookId===11&&__readerTest.state.reader.text.startsWith('ALICE ONLY')&&__readerTest.state.data.recents[0].id===11));
mode='text-error';await p.keyboard.press('Escape');await p.locator('[data-action=open-book]').click();await p.waitForSelector('[data-action=retry-open-book]',{timeout:5000});check('failed content offers reachable Retry without erasing saved place',await p.locator('[data-action=retry-open-book]').isVisible()&&await p.evaluate(()=>!__readerTest.state.reader.ready));mode='';await p.locator('[data-action=retry-open-book]').click();await p.waitForFunction(()=>__readerTest.state.reader.ready);check('retry can recover normally',true);
const longResult=await p.evaluate(()=>{const r=__readerTest.state.reader,old=r.text,oldAnchor=r.anchorOffset;r.text=('https://example.test/'+ 'abcdefghij'.repeat(350))+'\n\n'+('漢字🌿 café naïve '.repeat(120));r.anchorOffset=0;__readerTest.rebuild();const inner=document.querySelector('#reader-page-inner'),box=document.querySelector('#reader-page');let overflow=false,broken=false;r.pages.forEach(html=>{inner.innerHTML=html;overflow ||= inner.scrollHeight>box.clientHeight+1||inner.scrollWidth>box.clientWidth+1;broken ||= /[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/.test(inner.textContent);});r.text=old;__readerTest.rebuild();__readerTest.seek(oldAnchor);return{overflow,broken};});check('long unbroken text and Unicode paginate without overflow or broken surrogate pairs',!longResult.overflow&&!longResult.broken);
check('all personal writes retain the isolated device identity',writes.every(w=>w.identity===identity));await c.close();
for(const width of [390,320]){const c=await browser.newContext({viewport:{width,height:844},isMobile:true,hasTouch:true});await route(c);const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:5213/?test=1');await p.waitForTimeout(150);await p.screenshot({path:path.join(OUT,`home-${width}.png`)});await p.locator('[data-action=go-browse]').tap();await p.waitForTimeout(100);await p.screenshot({path:path.join(OUT,`browse-${width}.png`)});check(`${width}px real mobile library has no horizontal overflow`,await p.evaluate(()=>document.documentElement.scrollWidth<=visualViewport.width));await p.locator('.book-item').first().tap();await p.locator('[data-action=open-book]').tap();await p.waitForFunction(()=>__readerTest.state.reader.ready);await p.locator('#page-forward').tap();check(`${width}px touch turns reader pages`,await p.evaluate(()=>__readerTest.state.reader.currentPage===1));await p.screenshot({path:path.join(OUT,`reader-${width}.png`)});await p.locator('button[data-action=open-reader-menu]').tap();await p.screenshot({path:path.join(OUT,`menu-${width}.png`)});check(`${width}px menu and Back to reading fit viewport`,await p.evaluate(()=>{const e=document.querySelector('#reader-menu'),r=e.getBoundingClientRect();return r.left>=8&&r.right<=visualViewport.width-8&&r.bottom<=visualViewport.height-8;}));await c.close();}
check('no JavaScript errors',errors.length===0);console.log(`${checks.length} frontend checks passed`);
}finally{fs.writeFileSync(path.join(OUT,'report.json'),JSON.stringify({checks,errors,writes},null,2));await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
